/-
Copyright (c) 2025 Joël Riou. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Joël Riou
-/
module

public import Mathlib.AlgebraicTopology.SimplexCategory.Truncated

/-!
# Properties of morphisms in the simplex category

In this file, we show that morphisms in the simplex category
are generated by faces and degeneracies. This is stated by
saying that if `W : MorphismProperty SimplexCategory` is
multiplicative, and contains faces and degeneracies, then `W = ⊤`.
This statement is deduced from a similar statement for
the category `SimplexCategory.Truncated d`, which is itself obtained
by showing that such a `W` contains all epimorphisms
(`Truncated.mem_of_epi`) and all monomorphisms (`Truncated.mem_of_mono`).

-/

public section

open CategoryTheory Limits

namespace SimplexCategory

namespace Truncated

variable {d : ℕ} (W : MorphismProperty (Truncated d)) [W.IsMultiplicative]

/-- A multiplicative property of morphisms in `Truncated d` which contains the degeneracies
contains all epimorphisms. -/
lemma mem_of_epi (σ_mem : ∀ (n : ℕ) (hn : n < d) (i : Fin (n + 1)),
      W (Truncated.σ d i (by dsimp; lia) (by dsimp; lia)))
    {a b : Truncated d} (f : a ⟶ b) [hf : Epi f] : W f := by
  obtain ⟨⟨a⟩, ha⟩ := a
  obtain ⟨⟨b⟩, hb⟩ := b
  rw [epi_iff] at hf
  obtain ⟨c, rfl⟩ := Nat.exists_eq_add_of_le (len_le_of_epi f.hom)
  induction c with
  | zero => exact ObjectProperty.hom_ext _ (eq_id_of_epi f.hom) ▸ W.id_mem _
  | succ c hc =>
    obtain ⟨i, g, hg⟩ := eq_σ_comp_of_not_injective f.hom fun h ↦ by
      have := mono_iff_injective.2 h; have := len_le_of_mono f.hom; dsimp at this; lia
    have hc' : b + c < d := by dsimp at ha; lia
    rw [show f = Hom.tr (SimplexCategory.σ i) ≫ Hom.tr g hc'.le hb from InducedCategory.hom_ext hg]
    exact W.comp_mem _ _ (σ_mem _ hc' _) (@hc hc'.le _ (epi_of_epi_fac hg.symm))

/-- A multiplicative property of morphisms in `Truncated d` which contains the faces
contains all monomorphisms. -/
lemma mem_of_mono (δ_mem : ∀ (n : ℕ) (hn : n < d) (i : Fin (n + 2)),
      W (Truncated.δ d i (by dsimp; lia) (by dsimp; lia)))
    {a b : Truncated d} (f : a ⟶ b) [hf : Mono f] : W f := by
  obtain ⟨⟨a⟩, ha⟩ := a
  obtain ⟨⟨b⟩, hb⟩ := b
  rw [mono_iff] at hf
  obtain ⟨c, rfl⟩ := Nat.exists_eq_add_of_le (len_le_of_mono f.hom)
  induction c with
  | zero => exact ObjectProperty.hom_ext _ (eq_id_of_mono f.hom) ▸ W.id_mem _
  | succ c hc =>
    obtain ⟨i, g, hg⟩ := eq_comp_δ_of_not_surjective f.hom fun h ↦ by
      have := epi_iff_surjective.2 h; have := len_le_of_epi f.hom; dsimp at this; lia
    have hc' : a + c < d := by dsimp at hb; lia
    rw [show f = Hom.tr g ha hc'.le ≫ Hom.tr (SimplexCategory.δ i) from InducedCategory.hom_ext hg]
    exact W.comp_mem _ _ (@hc hc'.le _ (mono_of_mono_fac hg.symm)) (δ_mem _ hc' _)

lemma morphismProperty_eq_top
    (δ_mem : ∀ (n : ℕ) (hn : n < d) (i : Fin (n + 2)),
      W (Truncated.δ d i (by dsimp; lia) (by dsimp; lia)))
    (σ_mem : ∀ (n : ℕ) (hn : n < d) (i : Fin (n + 1)),
      W (Truncated.σ d i (by dsimp; lia) (by dsimp; lia))) :
    W = ⊤ := by
  ext a b f
  simp only [MorphismProperty.top_apply, iff_true]
  let I : Truncated d := ⟨image f.hom, (len_le_of_epi (factorThruImage f.hom)).trans a.2⟩
  rw [show f = ObjectProperty.homMk (X := a) (Y := I) (factorThruImage f.hom) ≫
    ObjectProperty.homMk (image.ι f.hom) from InducedCategory.hom_ext (image.fac f.hom).symm]
  exact W.comp_mem _ _ (@mem_of_epi _ W _ σ_mem _ _ _ (epi_iff.2 (by dsimp; infer_instance)))
    (@mem_of_mono _ W _ δ_mem _ _ _ (mono_iff.2 (by dsimp; infer_instance)))

end Truncated

lemma morphismProperty_eq_top
    (W : MorphismProperty SimplexCategory) [W.IsMultiplicative]
    (δ_mem : ∀ {n : ℕ} (i : Fin (n + 2)), W (SimplexCategory.δ i))
    (σ_mem : ∀ {n : ℕ} (i : Fin (n + 1)), W (SimplexCategory.σ i)) :
    W = ⊤ := by
  have hW (d : ℕ) : W.inverseImage (Truncated.inclusion d) = ⊤ :=
    Truncated.morphismProperty_eq_top _ (fun _ _ i ↦ δ_mem i)
      (fun _ _ i ↦ σ_mem i)
  ext a b f
  simp only [MorphismProperty.top_apply, iff_true]
  change W.inverseImage (Truncated.inclusion (max a.len b.len))
    (Truncated.Hom.tr f (ha := by simp) (hb := by simp))
  simp only [hW, MorphismProperty.top_apply]

end SimplexCategory
